import type { NextPage } from "next";
import Head from "next/head";

import { WorkExperience } from "../components/WorkExperience/WorkExperience";
import { Header } from "../components/Header/Header";
import { Hero } from "../components/Hero/Hero";
import { About } from "../components/About/About";
import { TechsAndTools } from "../components/Skills/TechsAndTools";

const Home: NextPage = () => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Fernando Lima - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section id={"hero"} className={"snap-start"}>
        <Hero />
      </section>

      <section id={"about"} className={"snap-center"}>
        <About />
      </section>

      <section id={"experience"} className={"snap-center"}>
        <WorkExperience />
      </section>

      <section id={"techs-and-tools"} className={"snap-center"}>
        <TechsAndTools />
      </section>
    </div>
  );
};

export default Home;
